;; Mock of SP1PFR4V08H1RAZXREBGFFQ59WB739XM8VVGTFSEA.dlmm-core-v-1-1.
;; `swap-y-for-x` reproduces the deployed arithmetic (read 2026-09-19); the bin
;; price uses a linear factor instead of the on-chain factor table.
(define-constant ERR_NO_POOL_DATA (err u1008))
(define-constant ERR_POOL_DISABLED (err u1010))
(define-constant ERR_INVALID_AMOUNT (err u1002))
(define-constant ERR_NOT_ACTIVE_BIN (err u1047))
(define-constant ERR_INVALID_BIN_PRICE (err u1045))
(define-constant ERR_INVALID_X_TOKEN (err u1018))
(define-constant ERR_INVALID_Y_TOKEN (err u1019))
(define-constant CENTER_BIN_ID u500)
(define-constant MAX_BIN_ID 500)
(define-constant FEE_SCALE_BPS u10000)
(define-constant PRICE_SCALE_BPS u100000000)

(define-data-var pool-status bool true)
(define-public (mock-set-status (s bool)) (begin (asserts! true (err u1)) (ok (var-set pool-status s))))

;; Real core: (ok (map-get? pools id)) -> (response (optional pool) ...)
(define-read-only (get-pool-by-id (id uint))
  (ok (if (is-eq id u6)
    (some {id: u6, name: "STX-sBTC-LP", symbol: "STX-sBTC", pool-contract: .dlmm-pool-stx-sbtc-v-1-bps-15, status: (var-get pool-status)})
    none)))

;; Linear stand-in for the factor table: 15 bps per bin around the center.
(define-read-only (get-bin-price (initial-price uint) (bin-step uint) (bin-id int))
  (let ((factor (+ 10000 (* (to-int bin-step) bin-id))))
    (asserts! (> factor 0) ERR_INVALID_BIN_PRICE)
    (ok (/ (* initial-price (to-uint factor)) u10000))))

(define-public (swap-y-for-x (pool principal) (x-token principal) (y-token principal) (bin-id int) (y-amount uint))
  (let (
      (caller tx-sender)
      (pool-data (unwrap! (contract-call? .dlmm-pool-stx-sbtc-v-1-bps-15 get-pool-for-swap false) ERR_NO_POOL_DATA))
      (active-bin-id (get active-bin-id pool-data))
      (swap-fee-total (+ (get protocol-fee pool-data) (get provider-fee pool-data) (get variable-fee pool-data)))
      (unsigned-bin-id (to-uint (+ bin-id (to-int CENTER_BIN_ID))))
      (bin-balances (unwrap-panic (contract-call? .dlmm-pool-stx-sbtc-v-1-bps-15 get-bin-balances unsigned-bin-id)))
      (x-balance (get x-balance bin-balances))
      (y-balance (get y-balance bin-balances))
      (initial-bin-balances-empty (and (is-eq x-balance u0) (is-eq y-balance u0)))
      (bin-price (unwrap! (get-bin-price (get initial-price pool-data) (get bin-step pool-data) bin-id) ERR_INVALID_BIN_PRICE))
      (max-y-amount (/ (+ (* x-balance bin-price) (- PRICE_SCALE_BPS u1)) PRICE_SCALE_BPS))
      (updated-max-y-amount (if (> swap-fee-total u0) (/ (* max-y-amount FEE_SCALE_BPS) (- FEE_SCALE_BPS swap-fee-total)) max-y-amount))
      (updated-y-amount (if (>= y-amount updated-max-y-amount) updated-max-y-amount y-amount))
      (y-amount-fees-total (/ (* updated-y-amount swap-fee-total) FEE_SCALE_BPS))
      (dy (- updated-y-amount y-amount-fees-total))
      (dx-before-cap (/ (* dy PRICE_SCALE_BPS) bin-price))
      (dx (if (> dx-before-cap x-balance) x-balance dx-before-cap))
      (updated-x-balance (- x-balance dx))
      (updated-y-balance (+ y-balance dy (- y-amount-fees-total (/ (* updated-y-amount (get protocol-fee pool-data)) FEE_SCALE_BPS))))
      (updated-active-bin-id (if (and (or (is-eq updated-x-balance u0) initial-bin-balances-empty) (< bin-id MAX_BIN_ID)) (+ bin-id 1) bin-id))
    )
    (asserts! (var-get pool-status) ERR_POOL_DISABLED)
    (asserts! (is-eq x-token .token-stx-v-1-2) ERR_INVALID_X_TOKEN)
    (asserts! (is-eq y-token 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token) ERR_INVALID_Y_TOKEN)
    (asserts! (> y-amount u0) ERR_INVALID_AMOUNT)
    (asserts! (is-eq bin-id active-bin-id) ERR_NOT_ACTIVE_BIN)
    (if (and (> updated-y-amount u0) (not initial-bin-balances-empty))
      (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer updated-y-amount caller .dlmm-pool-stx-sbtc-v-1-bps-15 none))
      false)
    (if (and (> dx u0) (not initial-bin-balances-empty))
      (try! (contract-call? .dlmm-pool-stx-sbtc-v-1-bps-15 pool-transfer .token-stx-v-1-2 dx caller))
      false)
    (if (and (> updated-y-amount u0) (not initial-bin-balances-empty))
      (try! (contract-call? .dlmm-pool-stx-sbtc-v-1-bps-15 update-bin-balances unsigned-bin-id updated-x-balance updated-y-balance))
      false)
    (if (not (is-eq updated-active-bin-id active-bin-id))
      (try! (contract-call? .dlmm-pool-stx-sbtc-v-1-bps-15 set-active-bin-id updated-active-bin-id))
      false)
    (print {action: "swap-y-for-x", caller: caller, data: {bin-id: bin-id, y-amount: y-amount, in: updated-y-amount, out: dx, updated-active-bin-id: updated-active-bin-id}})
    (ok {in: updated-y-amount, out: dx})))
