;; Simnet stand-in for SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.markets-sbtc-stx-jing-v6
;; (token-x = sBTC, token-y = STX). Reproduces the maker side the manager
;; drives: deposit-token-x (rest at a limit, park the smallest when the side
;; is full), cancel-token-x-deposit (refund resting, else parked),
;; set-token-x-limit, swap as taker (deposit, settle at the mock price against
;; the STX side, refund a leftover below the minimum, fail a larger one), and
;; the pro-rata distribution of a settlement with rollover into the next
;; cycle, refund below the minimum, STX pushed to makers. The Lazer update is
;; accepted and ignored; `mock-set-price` sets the clearing price.
;; Token arguments are principals here (the deployed market takes a SIP-010
;; trait); the manager passes contract principals either way.
(define-constant MAX_DEPOSITORS u50)
(define-constant FEE_BPS u10)
(define-constant TAKER_REBATE_BPS u20)
(define-constant BPS_PRECISION u10000)
(define-constant PRICE_PRECISION u100000000)
(define-constant DECIMAL_FACTOR u100)
(define-constant ERR_DEPOSIT_TOO_SMALL (err u1001))
(define-constant ERR_NOTHING_TO_WITHDRAW (err u1005))
(define-constant ERR_PAUSED (err u1007))
(define-constant ERR_NOTHING_TO_SETTLE (err u1009))
(define-constant ERR_QUEUE_FULL (err u1010))
(define-constant ERR_LIMIT_REQUIRED (err u1011))
(define-constant ERR_WRONG_TRAIT (err u1013))
(define-constant ERR_MUST_USE_SWAP (err u1016))
(define-constant ERR_PARTIAL_FILL (err u1017))
(define-constant ERR_HAS_RESTING_POSITION (err u1018))

(define-data-var paused bool false)
(define-data-var min-token-x-deposit uint u1000)
(define-data-var min-token-y-deposit uint u1000000)
(define-data-var current-cycle uint u3)
(define-data-var price uint u31390486455069) ;; STX per BTC x 1e8
(define-data-var bumped principal tx-sender)
(define-map token-x-deposits {cycle: uint, depositor: principal} uint)
(define-map token-x-depositor-list uint (list 50 principal))
(define-map token-x-deposit-limits principal {limit: uint, spread-bps: (optional uint)})
(define-map token-x-parked principal uint)
(define-map cycle-totals uint {total-token-y: uint, total-token-x: uint})
(define-map settlements uint {price: uint, token-y-cleared: uint, token-x-cleared: uint, token-y-fee: uint, token-x-fee: uint, settled-at: uint})
;; settlement scratch
(define-data-var s-total-x uint u0)
(define-data-var s-x-cleared uint u0)
(define-data-var s-y-after-fee uint u0)
(define-data-var s-caller-y uint u0)
(define-data-var s-caller-x-rolled uint u0)

(define-read-only (get-current-cycle) (var-get current-cycle))
(define-read-only (get-cycle-totals (cycle uint)) (default-to {total-token-y: u0, total-token-x: u0} (map-get? cycle-totals cycle)))
(define-read-only (get-settlement (cycle uint)) (map-get? settlements cycle))
(define-read-only (get-token-x-deposit (cycle uint) (depositor principal)) (default-to u0 (map-get? token-x-deposits {cycle: cycle, depositor: depositor})))
(define-read-only (get-token-x-parked (who principal)) (default-to u0 (map-get? token-x-parked who)))
(define-read-only (get-token-x-depositors (cycle uint)) (default-to (list) (map-get? token-x-depositor-list cycle)))
(define-read-only (get-token-x-order (depositor principal)) (default-to {limit: u0, spread-bps: none} (map-get? token-x-deposit-limits depositor)))
(define-read-only (get-token-x-limit (depositor principal)) (get limit (get-token-x-order depositor)))
(define-read-only (get-min-deposits) {min-token-y: (var-get min-token-y-deposit), min-token-x: (var-get min-token-x-deposit)})
(define-public (refresh-mid (update (buff 8192))) (begin (asserts! true (err u1)) (ok (var-get price))))

(define-private (not-bumped (p principal)) (not (is-eq p (var-get bumped))))
(define-private (add-depositor (cycle uint) (who principal))
  (if (is-some (index-of? (get-token-x-depositors cycle) who)) true
    (begin (map-set token-x-depositor-list cycle (unwrap-panic (as-max-len? (append (get-token-x-depositors cycle) who) u50))) true)))
(define-private (smallest-fold (d principal) (acc {cycle: uint, smallest: uint, who: principal}))
  (let ((a (get-token-x-deposit (get cycle acc) d)))
    (if (< a (get smallest acc)) (merge acc {smallest: a, who: d}) acc)))

;; Maker deposit. Parks the smallest existing maker when the side is full.
(define-public (deposit-token-x (amount uint) (limit-price uint) (spread-bps (optional uint)) (update (buff 8192)) (t principal) (asset-name (string-ascii 128)))
  (let ((cycle (var-get current-cycle)) (existing (get-token-x-deposit cycle tx-sender)) (parked (get-token-x-parked tx-sender))
        (depositors (get-token-x-depositors cycle)) (totals (get-cycle-totals cycle)))
    (asserts! (not (var-get paused)) ERR_PAUSED)
    (asserts! (is-eq t 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token) ERR_WRONG_TRAIT)
    (asserts! (> limit-price u0) ERR_LIMIT_REQUIRED)
    (asserts! (>= (+ existing parked amount) (var-get min-token-x-deposit)) ERR_DEPOSIT_TOO_SMALL)
    ;; a resting limit at or under the mock price would cross: must use swap
    (asserts! (or (is-eq (get total-token-y totals) u0) (> limit-price (var-get price))) ERR_MUST_USE_SWAP)
    (if (and (is-eq existing u0) (>= (len depositors) MAX_DEPOSITORS))
      (let ((sm (fold smallest-fold depositors {cycle: cycle, smallest: u999999999999999999, who: tx-sender})))
        (asserts! (> (+ parked amount) (get smallest sm)) ERR_QUEUE_FULL)
        (map-set token-x-parked (get who sm) (get smallest sm))
        (map-delete token-x-deposits {cycle: cycle, depositor: (get who sm)})
        (var-set bumped (get who sm))
        (map-set token-x-depositor-list cycle (filter not-bumped depositors))
        (map-set cycle-totals cycle (merge (get-cycle-totals cycle) {total-token-x: (- (get total-token-x (get-cycle-totals cycle)) (get smallest sm))}))
        true)
      true)
    (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer amount tx-sender current-contract none))
    (map-delete token-x-parked tx-sender)
    (map-set token-x-deposits {cycle: cycle, depositor: tx-sender} (+ existing parked amount))
    (add-depositor cycle tx-sender)
    (map-set token-x-deposit-limits tx-sender {limit: limit-price, spread-bps: spread-bps})
    (map-set cycle-totals cycle (merge (get-cycle-totals cycle) {total-token-x: (+ (get total-token-x (get-cycle-totals cycle)) parked amount)}))
    (ok (+ existing parked amount))))

;; Refund the resting amount; when nothing rests, the parked amount.
(define-public (cancel-token-x-deposit (t principal) (asset-name (string-ascii 128)))
  (let ((cycle (var-get current-cycle)) (caller tx-sender) (amount (get-token-x-deposit cycle caller)) (parked (get-token-x-parked caller)) (totals (get-cycle-totals cycle)))
    (asserts! (is-eq t 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token) ERR_WRONG_TRAIT)
    (asserts! (or (> amount u0) (> parked u0)) ERR_NOTHING_TO_WITHDRAW)
    (if (is-eq amount u0)
      (begin
        (try! (as-contract? ((with-ft 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token "sbtc-token" parked)) (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer parked current-contract caller none))))
        (map-delete token-x-parked caller) (map-delete token-x-deposit-limits caller)
        (ok parked))
      (begin
        (try! (as-contract? ((with-ft 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token "sbtc-token" amount)) (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer amount current-contract caller none))))
        (map-delete token-x-deposits {cycle: cycle, depositor: caller}) (map-delete token-x-deposit-limits caller)
        (var-set bumped caller)
        (map-set token-x-depositor-list cycle (filter not-bumped (get-token-x-depositors cycle)))
        (map-set cycle-totals cycle (merge totals {total-token-x: (- (get total-token-x totals) amount)}))
        (ok amount)))))

(define-public (set-token-x-limit (limit-price uint) (spread-bps (optional uint)) (update (buff 8192)))
  (begin
    (asserts! (> limit-price u0) ERR_LIMIT_REQUIRED)
    (asserts! (or (> (get-token-x-deposit (var-get current-cycle) tx-sender) u0) (> (get-token-x-parked tx-sender) u0)) ERR_NOTHING_TO_WITHDRAW)
    (asserts! (or (is-eq (get total-token-y (get-cycle-totals (var-get current-cycle))) u0) (> limit-price (var-get price))) ERR_MUST_USE_SWAP)
    (map-set token-x-deposit-limits tx-sender {limit: limit-price, spread-bps: spread-bps})
    (ok true)))

;; ---- test controls
(define-public (mock-set-price (p uint)) (begin (asserts! true (err u1)) (ok (var-set price p))))
(define-public (mock-set-paused (p bool)) (begin (asserts! true (err u1)) (ok (var-set paused p))))
(define-public (mock-set-min-x (m uint)) (begin (asserts! true (err u1)) (ok (var-set min-token-x-deposit m))))
;; STX bids for the current cycle (transferred in by the test).
(define-public (mock-buy (stx uint))
  (let ((cycle (var-get current-cycle)) (totals (get-cycle-totals cycle)))
    (try! (stx-transfer? stx tx-sender current-contract))
    (ok (map-set cycle-totals cycle (merge totals {total-token-y: (+ (get total-token-y totals) stx)})))))
;; Remove every resting STX bid of the current cycle (test reset).
(define-public (mock-drain-bids)
  (let ((cycle (var-get current-cycle)) (totals (get-cycle-totals cycle)) (y (get total-token-y totals)) (to tx-sender))
    (asserts! true (err u1))
    (if (> y u0) (unwrap-panic (pay-stx y to)) true)
    (ok (map-set cycle-totals cycle (merge totals {total-token-y: u0})))))
;; Park a maker as a larger deposit would.
(define-public (mock-park (who principal))
  (let ((cycle (var-get current-cycle)) (a (get-token-x-deposit cycle who)) (totals (get-cycle-totals cycle)))
    (asserts! (> a u0) ERR_NOTHING_TO_WITHDRAW)
    (map-set token-x-parked who (+ (get-token-x-parked who) a))
    (map-delete token-x-deposits {cycle: cycle, depositor: who})
    (var-set bumped who)
    (map-set token-x-depositor-list cycle (filter not-bumped (get-token-x-depositors cycle)))
    (ok (map-set cycle-totals cycle (merge totals {total-token-x: (- (get total-token-x totals) a)})))))

;; Settle the current cycle at the mock price: makers whose limit is above the
;; price roll; the rest clear pro rata against the STX side; STX pushed;
;; remainder rolled to the next cycle, refunded when below the minimum.
(define-public (mock-settle)
  (settle-core false))

(define-private (settle-core (crossing bool))
  (let ((cycle (var-get current-cycle)) (p (var-get price)))
    (map filter-limit (get-token-x-depositors cycle))
    (let ((totals (get-cycle-totals cycle)) (total-y (get total-token-y totals)) (total-x (get total-token-x totals))
          (x-value-in-y (/ (* total-x p) (* PRICE_PRECISION DECIMAL_FACTOR)))
          (x-binding (<= x-value-in-y total-y))
          (y-clearing (if x-binding x-value-in-y total-y))
          (x-clearing (if x-binding total-x (/ (* total-y (* PRICE_PRECISION DECIMAL_FACTOR)) p)))
          (y-fee (/ (* y-clearing FEE_BPS) BPS_PRECISION)))
      (asserts! (and (> total-y u0) (> total-x u0)) ERR_NOTHING_TO_SETTLE)
      (map-set settlements cycle {price: p, token-y-cleared: y-clearing, token-x-cleared: x-clearing, token-y-fee: y-fee, token-x-fee: (/ (* x-clearing FEE_BPS) BPS_PRECISION), settled-at: stacks-block-height})
      (var-set s-total-x total-x) (var-set s-x-cleared x-clearing) (var-set s-y-after-fee (- y-clearing y-fee))
      (var-set s-caller-y u0) (var-set s-caller-x-rolled u0)
      (map distribute (get-token-x-depositors cycle))
      ;; the STX side: bids that were not spent stay for the next cycle
      (map-set cycle-totals (+ cycle u1) (merge (get-cycle-totals (+ cycle u1)) {total-token-y: (- total-y y-clearing)}))
      (map-delete token-x-depositor-list cycle)
      (var-set current-cycle (+ cycle u1))
      (print {event: "settlement", cycle: cycle, price: p, token-x-cleared: x-clearing, token-y-cleared: y-clearing})
      (ok {token-y-received: (var-get s-caller-y), token-x-rolled: (var-get s-caller-x-rolled)}))))

(define-private (filter-limit (d principal))
  (let ((cycle (var-get current-cycle)) (a (get-token-x-deposit cycle d)))
    (if (> (get-token-x-limit d) (var-get price)) (roll-one d a cycle) true)))
(define-private (roll-one (d principal) (amount uint) (cycle uint))
  (let ((next (+ cycle u1)))
    (map-set token-x-deposits {cycle: next, depositor: d} (+ (get-token-x-deposit next d) amount))
    (add-depositor next d)
    (map-set cycle-totals next (merge (get-cycle-totals next) {total-token-x: (+ (get total-token-x (get-cycle-totals next)) amount)}))
    (map-delete token-x-deposits {cycle: cycle, depositor: d})
    (var-set bumped d)
    (map-set token-x-depositor-list cycle (filter not-bumped (get-token-x-depositors cycle)))
    (map-set cycle-totals cycle (merge (get-cycle-totals cycle) {total-token-x: (- (get total-token-x (get-cycle-totals cycle)) amount)}))
    true))
(define-private (pay-stx (amount uint) (to principal))
  (as-contract? ((with-stx amount)) (try! (stx-transfer? amount current-contract to))))
(define-private (pay-sbtc (amount uint) (to principal))
  (as-contract? ((with-ft 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token "sbtc-token" amount)) (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer amount current-contract to none))))
(define-private (distribute (d principal))
  (let ((cycle (var-get current-cycle)) (my (get-token-x-deposit cycle d)) (total (var-get s-total-x))
        (my-y (if (> total u0) (/ (* my (var-get s-y-after-fee)) total) u0))
        (my-unfilled (if (> total u0) (/ (* my (- total (var-get s-x-cleared))) total) u0))
        (my-refund (if (and (> my-unfilled u0) (< my-unfilled (var-get min-token-x-deposit))) my-unfilled u0))
        (my-roll (- my-unfilled my-refund))
        (next (+ cycle u1)))
    (map-delete token-x-deposits {cycle: cycle, depositor: d})
    (if (is-eq d tx-sender) (begin (var-set s-caller-y my-y) (var-set s-caller-x-rolled my-unfilled) true) true)
    (if (> my-y u0) (unwrap-panic (pay-stx my-y d)) true)
    (if (> my-roll u0)
      (begin (map-set token-x-deposits {cycle: next, depositor: d} my-roll) (add-depositor next d)
        (map-set cycle-totals next (merge (get-cycle-totals next) {total-token-x: (+ (get total-token-x (get-cycle-totals next)) my-roll)})) true)
      (begin (map-delete token-x-deposit-limits d)
        (if (> my-refund u0) (unwrap-panic (pay-sbtc my-refund d)) true)))
    (print {event: "distribute-x", depositor: d, cycle: cycle, stx-received: my-y, x-rolled: my-roll, x-refunded: my-refund})
    true))

;; Taker: rest net (amount minus the rebate) at limit, settle at once, refund
;; the rebate, fail if the leftover is at or above the minimum, else refund it.
(define-public (swap (amount uint) (limit-price uint) (update (buff 8192)) (tx-trait principal) (tx-name (string-ascii 128)) (ty-trait principal) (ty-name (string-ascii 128)) (deposit-x bool))
  (let ((rebate (/ (* amount TAKER_REBATE_BPS) BPS_PRECISION)) (net (- amount rebate)) (cycle (var-get current-cycle)) (caller tx-sender))
    (asserts! deposit-x ERR_WRONG_TRAIT)
    (asserts! (is-eq tx-trait 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token) ERR_WRONG_TRAIT)
    (asserts! (not (var-get paused)) ERR_PAUSED)
    (asserts! (> net u0) ERR_DEPOSIT_TOO_SMALL)
    (asserts! (is-eq (get-token-x-deposit cycle caller) u0) ERR_HAS_RESTING_POSITION)
    (asserts! (is-eq (get-token-x-parked caller) u0) ERR_HAS_RESTING_POSITION)
    (asserts! (>= net (var-get min-token-x-deposit)) ERR_DEPOSIT_TOO_SMALL)
    (asserts! (> limit-price u0) ERR_LIMIT_REQUIRED)
    ;; the taker accepts the clearing price only if it is at or above the limit
    (asserts! (>= (var-get price) limit-price) ERR_MUST_USE_SWAP)
    (try! (contract-call? 'SN3VMHXEN64ZZF71JQ5VESXDWTR301XTTXGF4J8F1.sbtc-token transfer amount caller current-contract none))
    (map-set token-x-deposits {cycle: cycle, depositor: caller} net)
    (add-depositor cycle caller)
    (map-set token-x-deposit-limits caller {limit: limit-price, spread-bps: none})
    (map-set cycle-totals cycle (merge (get-cycle-totals cycle) {total-token-x: (+ (get total-token-x (get-cycle-totals cycle)) net)}))
    (let ((result (try! (settle-core true)))
          (rem (get-token-x-deposit (var-get current-cycle) caller)))
      ;; unused rebate back
      (unwrap-panic (pay-sbtc rebate caller))
      (asserts! (< rem (var-get min-token-x-deposit)) ERR_PARTIAL_FILL)
      (if (> rem u0)
        (begin (unwrap-panic (pay-sbtc rem caller))
          (map-delete token-x-deposits {cycle: (var-get current-cycle), depositor: caller})
          (var-set bumped caller)
          (map-set token-x-depositor-list (var-get current-cycle) (filter not-bumped (get-token-x-depositors (var-get current-cycle))))
          (map-set cycle-totals (var-get current-cycle) (merge (get-cycle-totals (var-get current-cycle)) {total-token-x: (- (get total-token-x (get-cycle-totals (var-get current-cycle))) rem)}))
          true)
        true)
      (map-delete token-x-deposit-limits caller)
      (ok {token-x-received: u0, token-y-rolled: u0, token-y-received: (get token-y-received result), token-x-rolled: rem, rebate-refunded: rebate}))))
