;; Mock of SP20X3DC5R091J8B6YPQT638J8NR1W83KN6TN5BJY.univ2-fees-v1_0_0-0070 (calc-fees identical).
(define-constant err-calc-fees (err u997))
(define-data-var state {swap-fee: {num: uint, den: uint}, protocol-fee: {num: uint, den: uint}}
  {swap-fee: {num: u9970, den: u10000}, protocol-fee: {num: u2500, den: u10000}})
(define-data-var revenue {token0: uint, token1: uint} {token0: u0, token1: u0})
(define-public (mock-set-swap-fee (num uint)) (begin (asserts! true (err u1)) (ok (var-set state (merge (var-get state) {swap-fee: {num: num, den: u10000}})))))
(define-read-only (get-fees) (ok (var-get state)))
(define-public (receive (is-token0 bool) (amt uint))
  (let ((r (var-get revenue)))
    (asserts! true (err u1))
    (ok (var-set revenue (if is-token0 {token0: (+ (get token0 r) amt), token1: (get token1 r)} {token0: (get token0 r), token1: (+ (get token1 r) amt)})))))
(define-read-only (calc-fees (amt-in uint))
  (let ((state_ (var-get state)) (swap-fee (get swap-fee state_)) (protocol-fee (get protocol-fee state_))
        (amt-in-adjusted (/ (* amt-in (get num swap-fee)) (get den swap-fee)))
        (amt-fee-total (- amt-in amt-in-adjusted))
        (amt-fee-protocol (/ (* amt-fee-total (get num protocol-fee)) (get den protocol-fee)))
        (amt-fee-lps (- amt-fee-total amt-fee-protocol)))
    (asserts! (and (or (is-eq (get num swap-fee) (get den swap-fee)) (and (> amt-fee-lps u0)) (or (is-eq (get num protocol-fee) (get den protocol-fee)) (> amt-fee-protocol u0)))
                   (is-eq amt-in (+ amt-in-adjusted amt-fee-lps amt-fee-protocol))) err-calc-fees)
    (ok {amt-in-adjusted: amt-in-adjusted, amt-fee-lps: amt-fee-lps, amt-fee-protocol: amt-fee-protocol})))
