;; Zero to Claiming batch helper, uint-return shape, revision 2. One transaction
;; claims for up to 200 stakers against a manager whose claim-staker-rewards
;; returns a bare uint (the earlier reference revision that Xverse's deployment
;; froze). Same contract as revision 1 (zc-claim-helper-uint) with the list
;; capacity raised; deployed alongside it, never replacing it.
;;
;; Capacity 200, sized from mainnet measurements of the 50-entry revision
;; (2026-09-10, Fastpool max500, 25-entry batches, block limits read_count
;; 15,000 / read_length 100M / runtime 5e9 / write_count 15,000 / write_length
;; 15M): settle-many cost 27 reads, 180 KB read length, 234k runtime and 8
;; writes per entry; payout-many 14 reads and 4 writes per sBTC entry, about 34
;; reads and 10 writes per BTC entry. At 200 entries the heaviest case (all-BTC
;; payouts) sits near 45 percent of the block's read count and settles near 36
;; percent of read length, under the 75 percent ceiling the app targets; the
;; rest of the dimensions stay below 15 percent.
;;
;; Same design rules as zc-claim-helper-v2: error isolation via match, never
;; try!; the helper holds no funds and triggers only permissionless calls;
;; per-entry prints plus a batch summary let the app reconcile results from the
;; transaction's events. The uint return carries no withdrawal request id; on
;; BTC payouts that id lives in the manager's own l1-withdrawal print event,
;; emitted in the same transaction. No settle-many or payout-many here: this
;; revision predates the settle-and-payout lineage and has neither function.

(define-trait claimable-manager-uint
  ((claim-staker-rewards (principal uint (optional uint)) (response uint uint))))

(define-private (claim-one-uint
    (m <claimable-manager-uint>)
    (oe (optional {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
  (match oe e
    (match (contract-call? m claim-staker-rewards (get staker e) (get reward-cycle e) (get bond-index e))
      r (begin
          (print {topic: "zc-claim-ok", staker: (get staker e), reward-cycle: (get reward-cycle e), earned: r})
          {ok: u1, err: u0})
      c (begin
          (print {topic: "zc-claim-err", staker: (get staker e), reward-cycle: (get reward-cycle e), code: c})
          {ok: u0, err: u1}))
    {ok: u0, err: u0}))

(define-public (claim-many
    (m <claimable-manager-uint>)
    (entries (list 200 {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
    (let (
            (r0 (claim-one-uint m (element-at? entries u0)))
            (r1 (claim-one-uint m (element-at? entries u1)))
            (r2 (claim-one-uint m (element-at? entries u2)))
            (r3 (claim-one-uint m (element-at? entries u3)))
            (r4 (claim-one-uint m (element-at? entries u4)))
            (r5 (claim-one-uint m (element-at? entries u5)))
            (r6 (claim-one-uint m (element-at? entries u6)))
            (r7 (claim-one-uint m (element-at? entries u7)))
            (r8 (claim-one-uint m (element-at? entries u8)))
            (r9 (claim-one-uint m (element-at? entries u9)))
            (r10 (claim-one-uint m (element-at? entries u10)))
            (r11 (claim-one-uint m (element-at? entries u11)))
            (r12 (claim-one-uint m (element-at? entries u12)))
            (r13 (claim-one-uint m (element-at? entries u13)))
            (r14 (claim-one-uint m (element-at? entries u14)))
            (r15 (claim-one-uint m (element-at? entries u15)))
            (r16 (claim-one-uint m (element-at? entries u16)))
            (r17 (claim-one-uint m (element-at? entries u17)))
            (r18 (claim-one-uint m (element-at? entries u18)))
            (r19 (claim-one-uint m (element-at? entries u19)))
            (r20 (claim-one-uint m (element-at? entries u20)))
            (r21 (claim-one-uint m (element-at? entries u21)))
            (r22 (claim-one-uint m (element-at? entries u22)))
            (r23 (claim-one-uint m (element-at? entries u23)))
            (r24 (claim-one-uint m (element-at? entries u24)))
            (r25 (claim-one-uint m (element-at? entries u25)))
            (r26 (claim-one-uint m (element-at? entries u26)))
            (r27 (claim-one-uint m (element-at? entries u27)))
            (r28 (claim-one-uint m (element-at? entries u28)))
            (r29 (claim-one-uint m (element-at? entries u29)))
            (r30 (claim-one-uint m (element-at? entries u30)))
            (r31 (claim-one-uint m (element-at? entries u31)))
            (r32 (claim-one-uint m (element-at? entries u32)))
            (r33 (claim-one-uint m (element-at? entries u33)))
            (r34 (claim-one-uint m (element-at? entries u34)))
            (r35 (claim-one-uint m (element-at? entries u35)))
            (r36 (claim-one-uint m (element-at? entries u36)))
            (r37 (claim-one-uint m (element-at? entries u37)))
            (r38 (claim-one-uint m (element-at? entries u38)))
            (r39 (claim-one-uint m (element-at? entries u39)))
            (r40 (claim-one-uint m (element-at? entries u40)))
            (r41 (claim-one-uint m (element-at? entries u41)))
            (r42 (claim-one-uint m (element-at? entries u42)))
            (r43 (claim-one-uint m (element-at? entries u43)))
            (r44 (claim-one-uint m (element-at? entries u44)))
            (r45 (claim-one-uint m (element-at? entries u45)))
            (r46 (claim-one-uint m (element-at? entries u46)))
            (r47 (claim-one-uint m (element-at? entries u47)))
            (r48 (claim-one-uint m (element-at? entries u48)))
            (r49 (claim-one-uint m (element-at? entries u49)))
            (r50 (claim-one-uint m (element-at? entries u50)))
            (r51 (claim-one-uint m (element-at? entries u51)))
            (r52 (claim-one-uint m (element-at? entries u52)))
            (r53 (claim-one-uint m (element-at? entries u53)))
            (r54 (claim-one-uint m (element-at? entries u54)))
            (r55 (claim-one-uint m (element-at? entries u55)))
            (r56 (claim-one-uint m (element-at? entries u56)))
            (r57 (claim-one-uint m (element-at? entries u57)))
            (r58 (claim-one-uint m (element-at? entries u58)))
            (r59 (claim-one-uint m (element-at? entries u59)))
            (r60 (claim-one-uint m (element-at? entries u60)))
            (r61 (claim-one-uint m (element-at? entries u61)))
            (r62 (claim-one-uint m (element-at? entries u62)))
            (r63 (claim-one-uint m (element-at? entries u63)))
            (r64 (claim-one-uint m (element-at? entries u64)))
            (r65 (claim-one-uint m (element-at? entries u65)))
            (r66 (claim-one-uint m (element-at? entries u66)))
            (r67 (claim-one-uint m (element-at? entries u67)))
            (r68 (claim-one-uint m (element-at? entries u68)))
            (r69 (claim-one-uint m (element-at? entries u69)))
            (r70 (claim-one-uint m (element-at? entries u70)))
            (r71 (claim-one-uint m (element-at? entries u71)))
            (r72 (claim-one-uint m (element-at? entries u72)))
            (r73 (claim-one-uint m (element-at? entries u73)))
            (r74 (claim-one-uint m (element-at? entries u74)))
            (r75 (claim-one-uint m (element-at? entries u75)))
            (r76 (claim-one-uint m (element-at? entries u76)))
            (r77 (claim-one-uint m (element-at? entries u77)))
            (r78 (claim-one-uint m (element-at? entries u78)))
            (r79 (claim-one-uint m (element-at? entries u79)))
            (r80 (claim-one-uint m (element-at? entries u80)))
            (r81 (claim-one-uint m (element-at? entries u81)))
            (r82 (claim-one-uint m (element-at? entries u82)))
            (r83 (claim-one-uint m (element-at? entries u83)))
            (r84 (claim-one-uint m (element-at? entries u84)))
            (r85 (claim-one-uint m (element-at? entries u85)))
            (r86 (claim-one-uint m (element-at? entries u86)))
            (r87 (claim-one-uint m (element-at? entries u87)))
            (r88 (claim-one-uint m (element-at? entries u88)))
            (r89 (claim-one-uint m (element-at? entries u89)))
            (r90 (claim-one-uint m (element-at? entries u90)))
            (r91 (claim-one-uint m (element-at? entries u91)))
            (r92 (claim-one-uint m (element-at? entries u92)))
            (r93 (claim-one-uint m (element-at? entries u93)))
            (r94 (claim-one-uint m (element-at? entries u94)))
            (r95 (claim-one-uint m (element-at? entries u95)))
            (r96 (claim-one-uint m (element-at? entries u96)))
            (r97 (claim-one-uint m (element-at? entries u97)))
            (r98 (claim-one-uint m (element-at? entries u98)))
            (r99 (claim-one-uint m (element-at? entries u99)))
            (r100 (claim-one-uint m (element-at? entries u100)))
            (r101 (claim-one-uint m (element-at? entries u101)))
            (r102 (claim-one-uint m (element-at? entries u102)))
            (r103 (claim-one-uint m (element-at? entries u103)))
            (r104 (claim-one-uint m (element-at? entries u104)))
            (r105 (claim-one-uint m (element-at? entries u105)))
            (r106 (claim-one-uint m (element-at? entries u106)))
            (r107 (claim-one-uint m (element-at? entries u107)))
            (r108 (claim-one-uint m (element-at? entries u108)))
            (r109 (claim-one-uint m (element-at? entries u109)))
            (r110 (claim-one-uint m (element-at? entries u110)))
            (r111 (claim-one-uint m (element-at? entries u111)))
            (r112 (claim-one-uint m (element-at? entries u112)))
            (r113 (claim-one-uint m (element-at? entries u113)))
            (r114 (claim-one-uint m (element-at? entries u114)))
            (r115 (claim-one-uint m (element-at? entries u115)))
            (r116 (claim-one-uint m (element-at? entries u116)))
            (r117 (claim-one-uint m (element-at? entries u117)))
            (r118 (claim-one-uint m (element-at? entries u118)))
            (r119 (claim-one-uint m (element-at? entries u119)))
            (r120 (claim-one-uint m (element-at? entries u120)))
            (r121 (claim-one-uint m (element-at? entries u121)))
            (r122 (claim-one-uint m (element-at? entries u122)))
            (r123 (claim-one-uint m (element-at? entries u123)))
            (r124 (claim-one-uint m (element-at? entries u124)))
            (r125 (claim-one-uint m (element-at? entries u125)))
            (r126 (claim-one-uint m (element-at? entries u126)))
            (r127 (claim-one-uint m (element-at? entries u127)))
            (r128 (claim-one-uint m (element-at? entries u128)))
            (r129 (claim-one-uint m (element-at? entries u129)))
            (r130 (claim-one-uint m (element-at? entries u130)))
            (r131 (claim-one-uint m (element-at? entries u131)))
            (r132 (claim-one-uint m (element-at? entries u132)))
            (r133 (claim-one-uint m (element-at? entries u133)))
            (r134 (claim-one-uint m (element-at? entries u134)))
            (r135 (claim-one-uint m (element-at? entries u135)))
            (r136 (claim-one-uint m (element-at? entries u136)))
            (r137 (claim-one-uint m (element-at? entries u137)))
            (r138 (claim-one-uint m (element-at? entries u138)))
            (r139 (claim-one-uint m (element-at? entries u139)))
            (r140 (claim-one-uint m (element-at? entries u140)))
            (r141 (claim-one-uint m (element-at? entries u141)))
            (r142 (claim-one-uint m (element-at? entries u142)))
            (r143 (claim-one-uint m (element-at? entries u143)))
            (r144 (claim-one-uint m (element-at? entries u144)))
            (r145 (claim-one-uint m (element-at? entries u145)))
            (r146 (claim-one-uint m (element-at? entries u146)))
            (r147 (claim-one-uint m (element-at? entries u147)))
            (r148 (claim-one-uint m (element-at? entries u148)))
            (r149 (claim-one-uint m (element-at? entries u149)))
            (r150 (claim-one-uint m (element-at? entries u150)))
            (r151 (claim-one-uint m (element-at? entries u151)))
            (r152 (claim-one-uint m (element-at? entries u152)))
            (r153 (claim-one-uint m (element-at? entries u153)))
            (r154 (claim-one-uint m (element-at? entries u154)))
            (r155 (claim-one-uint m (element-at? entries u155)))
            (r156 (claim-one-uint m (element-at? entries u156)))
            (r157 (claim-one-uint m (element-at? entries u157)))
            (r158 (claim-one-uint m (element-at? entries u158)))
            (r159 (claim-one-uint m (element-at? entries u159)))
            (r160 (claim-one-uint m (element-at? entries u160)))
            (r161 (claim-one-uint m (element-at? entries u161)))
            (r162 (claim-one-uint m (element-at? entries u162)))
            (r163 (claim-one-uint m (element-at? entries u163)))
            (r164 (claim-one-uint m (element-at? entries u164)))
            (r165 (claim-one-uint m (element-at? entries u165)))
            (r166 (claim-one-uint m (element-at? entries u166)))
            (r167 (claim-one-uint m (element-at? entries u167)))
            (r168 (claim-one-uint m (element-at? entries u168)))
            (r169 (claim-one-uint m (element-at? entries u169)))
            (r170 (claim-one-uint m (element-at? entries u170)))
            (r171 (claim-one-uint m (element-at? entries u171)))
            (r172 (claim-one-uint m (element-at? entries u172)))
            (r173 (claim-one-uint m (element-at? entries u173)))
            (r174 (claim-one-uint m (element-at? entries u174)))
            (r175 (claim-one-uint m (element-at? entries u175)))
            (r176 (claim-one-uint m (element-at? entries u176)))
            (r177 (claim-one-uint m (element-at? entries u177)))
            (r178 (claim-one-uint m (element-at? entries u178)))
            (r179 (claim-one-uint m (element-at? entries u179)))
            (r180 (claim-one-uint m (element-at? entries u180)))
            (r181 (claim-one-uint m (element-at? entries u181)))
            (r182 (claim-one-uint m (element-at? entries u182)))
            (r183 (claim-one-uint m (element-at? entries u183)))
            (r184 (claim-one-uint m (element-at? entries u184)))
            (r185 (claim-one-uint m (element-at? entries u185)))
            (r186 (claim-one-uint m (element-at? entries u186)))
            (r187 (claim-one-uint m (element-at? entries u187)))
            (r188 (claim-one-uint m (element-at? entries u188)))
            (r189 (claim-one-uint m (element-at? entries u189)))
            (r190 (claim-one-uint m (element-at? entries u190)))
            (r191 (claim-one-uint m (element-at? entries u191)))
            (r192 (claim-one-uint m (element-at? entries u192)))
            (r193 (claim-one-uint m (element-at? entries u193)))
            (r194 (claim-one-uint m (element-at? entries u194)))
            (r195 (claim-one-uint m (element-at? entries u195)))
            (r196 (claim-one-uint m (element-at? entries u196)))
            (r197 (claim-one-uint m (element-at? entries u197)))
            (r198 (claim-one-uint m (element-at? entries u198)))
            (r199 (claim-one-uint m (element-at? entries u199)))
        )
        (let ((result {
                topic: "claim-many",
                manager: (contract-of m),
                submitted: (len entries),
                ok-count: (+ (get ok r0)
                    (get ok r1)
                    (get ok r2)
                    (get ok r3)
                    (get ok r4)
                    (get ok r5)
                    (get ok r6)
                    (get ok r7)
                    (get ok r8)
                    (get ok r9)
                    (get ok r10)
                    (get ok r11)
                    (get ok r12)
                    (get ok r13)
                    (get ok r14)
                    (get ok r15)
                    (get ok r16)
                    (get ok r17)
                    (get ok r18)
                    (get ok r19)
                    (get ok r20)
                    (get ok r21)
                    (get ok r22)
                    (get ok r23)
                    (get ok r24)
                    (get ok r25)
                    (get ok r26)
                    (get ok r27)
                    (get ok r28)
                    (get ok r29)
                    (get ok r30)
                    (get ok r31)
                    (get ok r32)
                    (get ok r33)
                    (get ok r34)
                    (get ok r35)
                    (get ok r36)
                    (get ok r37)
                    (get ok r38)
                    (get ok r39)
                    (get ok r40)
                    (get ok r41)
                    (get ok r42)
                    (get ok r43)
                    (get ok r44)
                    (get ok r45)
                    (get ok r46)
                    (get ok r47)
                    (get ok r48)
                    (get ok r49)
                    (get ok r50)
                    (get ok r51)
                    (get ok r52)
                    (get ok r53)
                    (get ok r54)
                    (get ok r55)
                    (get ok r56)
                    (get ok r57)
                    (get ok r58)
                    (get ok r59)
                    (get ok r60)
                    (get ok r61)
                    (get ok r62)
                    (get ok r63)
                    (get ok r64)
                    (get ok r65)
                    (get ok r66)
                    (get ok r67)
                    (get ok r68)
                    (get ok r69)
                    (get ok r70)
                    (get ok r71)
                    (get ok r72)
                    (get ok r73)
                    (get ok r74)
                    (get ok r75)
                    (get ok r76)
                    (get ok r77)
                    (get ok r78)
                    (get ok r79)
                    (get ok r80)
                    (get ok r81)
                    (get ok r82)
                    (get ok r83)
                    (get ok r84)
                    (get ok r85)
                    (get ok r86)
                    (get ok r87)
                    (get ok r88)
                    (get ok r89)
                    (get ok r90)
                    (get ok r91)
                    (get ok r92)
                    (get ok r93)
                    (get ok r94)
                    (get ok r95)
                    (get ok r96)
                    (get ok r97)
                    (get ok r98)
                    (get ok r99)
                    (get ok r100)
                    (get ok r101)
                    (get ok r102)
                    (get ok r103)
                    (get ok r104)
                    (get ok r105)
                    (get ok r106)
                    (get ok r107)
                    (get ok r108)
                    (get ok r109)
                    (get ok r110)
                    (get ok r111)
                    (get ok r112)
                    (get ok r113)
                    (get ok r114)
                    (get ok r115)
                    (get ok r116)
                    (get ok r117)
                    (get ok r118)
                    (get ok r119)
                    (get ok r120)
                    (get ok r121)
                    (get ok r122)
                    (get ok r123)
                    (get ok r124)
                    (get ok r125)
                    (get ok r126)
                    (get ok r127)
                    (get ok r128)
                    (get ok r129)
                    (get ok r130)
                    (get ok r131)
                    (get ok r132)
                    (get ok r133)
                    (get ok r134)
                    (get ok r135)
                    (get ok r136)
                    (get ok r137)
                    (get ok r138)
                    (get ok r139)
                    (get ok r140)
                    (get ok r141)
                    (get ok r142)
                    (get ok r143)
                    (get ok r144)
                    (get ok r145)
                    (get ok r146)
                    (get ok r147)
                    (get ok r148)
                    (get ok r149)
                    (get ok r150)
                    (get ok r151)
                    (get ok r152)
                    (get ok r153)
                    (get ok r154)
                    (get ok r155)
                    (get ok r156)
                    (get ok r157)
                    (get ok r158)
                    (get ok r159)
                    (get ok r160)
                    (get ok r161)
                    (get ok r162)
                    (get ok r163)
                    (get ok r164)
                    (get ok r165)
                    (get ok r166)
                    (get ok r167)
                    (get ok r168)
                    (get ok r169)
                    (get ok r170)
                    (get ok r171)
                    (get ok r172)
                    (get ok r173)
                    (get ok r174)
                    (get ok r175)
                    (get ok r176)
                    (get ok r177)
                    (get ok r178)
                    (get ok r179)
                    (get ok r180)
                    (get ok r181)
                    (get ok r182)
                    (get ok r183)
                    (get ok r184)
                    (get ok r185)
                    (get ok r186)
                    (get ok r187)
                    (get ok r188)
                    (get ok r189)
                    (get ok r190)
                    (get ok r191)
                    (get ok r192)
                    (get ok r193)
                    (get ok r194)
                    (get ok r195)
                    (get ok r196)
                    (get ok r197)
                    (get ok r198)
                    (get ok r199)),
                err-count: (+ (get err r0)
                    (get err r1)
                    (get err r2)
                    (get err r3)
                    (get err r4)
                    (get err r5)
                    (get err r6)
                    (get err r7)
                    (get err r8)
                    (get err r9)
                    (get err r10)
                    (get err r11)
                    (get err r12)
                    (get err r13)
                    (get err r14)
                    (get err r15)
                    (get err r16)
                    (get err r17)
                    (get err r18)
                    (get err r19)
                    (get err r20)
                    (get err r21)
                    (get err r22)
                    (get err r23)
                    (get err r24)
                    (get err r25)
                    (get err r26)
                    (get err r27)
                    (get err r28)
                    (get err r29)
                    (get err r30)
                    (get err r31)
                    (get err r32)
                    (get err r33)
                    (get err r34)
                    (get err r35)
                    (get err r36)
                    (get err r37)
                    (get err r38)
                    (get err r39)
                    (get err r40)
                    (get err r41)
                    (get err r42)
                    (get err r43)
                    (get err r44)
                    (get err r45)
                    (get err r46)
                    (get err r47)
                    (get err r48)
                    (get err r49)
                    (get err r50)
                    (get err r51)
                    (get err r52)
                    (get err r53)
                    (get err r54)
                    (get err r55)
                    (get err r56)
                    (get err r57)
                    (get err r58)
                    (get err r59)
                    (get err r60)
                    (get err r61)
                    (get err r62)
                    (get err r63)
                    (get err r64)
                    (get err r65)
                    (get err r66)
                    (get err r67)
                    (get err r68)
                    (get err r69)
                    (get err r70)
                    (get err r71)
                    (get err r72)
                    (get err r73)
                    (get err r74)
                    (get err r75)
                    (get err r76)
                    (get err r77)
                    (get err r78)
                    (get err r79)
                    (get err r80)
                    (get err r81)
                    (get err r82)
                    (get err r83)
                    (get err r84)
                    (get err r85)
                    (get err r86)
                    (get err r87)
                    (get err r88)
                    (get err r89)
                    (get err r90)
                    (get err r91)
                    (get err r92)
                    (get err r93)
                    (get err r94)
                    (get err r95)
                    (get err r96)
                    (get err r97)
                    (get err r98)
                    (get err r99)
                    (get err r100)
                    (get err r101)
                    (get err r102)
                    (get err r103)
                    (get err r104)
                    (get err r105)
                    (get err r106)
                    (get err r107)
                    (get err r108)
                    (get err r109)
                    (get err r110)
                    (get err r111)
                    (get err r112)
                    (get err r113)
                    (get err r114)
                    (get err r115)
                    (get err r116)
                    (get err r117)
                    (get err r118)
                    (get err r119)
                    (get err r120)
                    (get err r121)
                    (get err r122)
                    (get err r123)
                    (get err r124)
                    (get err r125)
                    (get err r126)
                    (get err r127)
                    (get err r128)
                    (get err r129)
                    (get err r130)
                    (get err r131)
                    (get err r132)
                    (get err r133)
                    (get err r134)
                    (get err r135)
                    (get err r136)
                    (get err r137)
                    (get err r138)
                    (get err r139)
                    (get err r140)
                    (get err r141)
                    (get err r142)
                    (get err r143)
                    (get err r144)
                    (get err r145)
                    (get err r146)
                    (get err r147)
                    (get err r148)
                    (get err r149)
                    (get err r150)
                    (get err r151)
                    (get err r152)
                    (get err r153)
                    (get err r154)
                    (get err r155)
                    (get err r156)
                    (get err r157)
                    (get err r158)
                    (get err r159)
                    (get err r160)
                    (get err r161)
                    (get err r162)
                    (get err r163)
                    (get err r164)
                    (get err r165)
                    (get err r166)
                    (get err r167)
                    (get err r168)
                    (get err r169)
                    (get err r170)
                    (get err r171)
                    (get err r172)
                    (get err r173)
                    (get err r174)
                    (get err r175)
                    (get err r176)
                    (get err r177)
                    (get err r178)
                    (get err r179)
                    (get err r180)
                    (get err r181)
                    (get err r182)
                    (get err r183)
                    (get err r184)
                    (get err r185)
                    (get err r186)
                    (get err r187)
                    (get err r188)
                    (get err r189)
                    (get err r190)
                    (get err r191)
                    (get err r192)
                    (get err r193)
                    (get err r194)
                    (get err r195)
                    (get err r196)
                    (get err r197)
                    (get err r198)
                    (get err r199)),
            }))
            (print result)
            (ok result))))
