;; Zero to Claiming batch helper. One transaction claims for up to 50 stakers.
;;
;; Design rules (claim-many.md):
;; - Error isolation is the whole design: every inner call is matched, counted,
;;   and printed, never try!'d, so one dust-sized or already-claimed staker
;;   cannot strand the rest of the batch. An inner err rolls back only that
;;   call's state; the batch continues.
;; - The helper holds no funds and triggers only permissionless calls. Rewards
;;   flow from the manager or pox-5 directly to stakers; nothing routes through
;;   this contract.
;; - Never batchable, by the managers' own design: set-payout-config,
;;   clear-payout-config, anything behind authorize-admin (all assert
;;   contract-caller equals tx-sender). This contract does not pretend otherwise.
;; - Tuple-shape managers only (Fastpool v1, Senseinode, Fastpool Max 500).
;;   Xverse's earlier revision returns a bare uint from claim-staker-rewards and
;;   does not fit this trait; it gets its own helper if demand exists.
;; - List capacity 50 per call; the app chunks larger selections and sizes
;;   batches empirically (start 25 for BTC-heavy, measure on testnet).
;; - The per-entry bodies below are mechanically unrolled: Clarity cannot carry
;;   a trait reference through fold or map, so each list slot is processed by an
;;   indexed call into the same private function.

(define-trait claimable-manager
  ((claim-staker-rewards (principal uint (optional uint))
    (response {earned: uint, withdrawal-request: (optional uint)} uint))))

(define-trait settleable-manager
  ((settle-staker-rewards (principal uint (optional uint)) (response uint uint))
   (payout (principal) (response {amount: uint, withdrawal-request: (optional uint)} uint))))

(define-private (claim-one
    (m <claimable-manager>)
    (oe (optional {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
  (match oe e
    (match (contract-call? m claim-staker-rewards (get staker e) (get reward-cycle e) (get bond-index e))
      r (begin
          (print {topic: "zc-claim-ok", staker: (get staker e), reward-cycle: (get reward-cycle e),
                  earned: (get earned r), withdrawal-request: (get withdrawal-request r)})
          {ok: u1, err: u0})
      c (begin
          (print {topic: "zc-claim-err", staker: (get staker e), reward-cycle: (get reward-cycle e), code: c})
          {ok: u0, err: u1}))
    {ok: u0, err: u0}))

(define-private (settle-one
    (m <settleable-manager>)
    (oe (optional {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
  (match oe e
    (match (contract-call? m settle-staker-rewards (get staker e) (get reward-cycle e) (get bond-index e))
      r (begin
          (print {topic: "zc-settle-ok", staker: (get staker e), reward-cycle: (get reward-cycle e), settled: r})
          {ok: u1, err: u0})
      c (begin
          (print {topic: "zc-settle-err", staker: (get staker e), reward-cycle: (get reward-cycle e), code: c})
          {ok: u0, err: u1}))
    {ok: u0, err: u0}))

(define-private (payout-one
    (m <settleable-manager>)
    (os (optional principal)))
  (match os s
    (match (contract-call? m payout s)
      r (begin
          (print {topic: "zc-payout-ok", staker: s, amount: (get amount r), withdrawal-request: (get withdrawal-request r)})
          {ok: u1, err: u0})
      c (begin
          (print {topic: "zc-payout-err", staker: s, code: c})
          {ok: u0, err: u1}))
    {ok: u0, err: u0}))

(define-public (claim-many
    (m <claimable-manager>)
    (entries (list 50 {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
    (let (
            (r0 (claim-one m (element-at? entries u0)))
            (r1 (claim-one m (element-at? entries u1)))
            (r2 (claim-one m (element-at? entries u2)))
            (r3 (claim-one m (element-at? entries u3)))
            (r4 (claim-one m (element-at? entries u4)))
            (r5 (claim-one m (element-at? entries u5)))
            (r6 (claim-one m (element-at? entries u6)))
            (r7 (claim-one m (element-at? entries u7)))
            (r8 (claim-one m (element-at? entries u8)))
            (r9 (claim-one m (element-at? entries u9)))
            (r10 (claim-one m (element-at? entries u10)))
            (r11 (claim-one m (element-at? entries u11)))
            (r12 (claim-one m (element-at? entries u12)))
            (r13 (claim-one m (element-at? entries u13)))
            (r14 (claim-one m (element-at? entries u14)))
            (r15 (claim-one m (element-at? entries u15)))
            (r16 (claim-one m (element-at? entries u16)))
            (r17 (claim-one m (element-at? entries u17)))
            (r18 (claim-one m (element-at? entries u18)))
            (r19 (claim-one m (element-at? entries u19)))
            (r20 (claim-one m (element-at? entries u20)))
            (r21 (claim-one m (element-at? entries u21)))
            (r22 (claim-one m (element-at? entries u22)))
            (r23 (claim-one m (element-at? entries u23)))
            (r24 (claim-one m (element-at? entries u24)))
            (r25 (claim-one m (element-at? entries u25)))
            (r26 (claim-one m (element-at? entries u26)))
            (r27 (claim-one m (element-at? entries u27)))
            (r28 (claim-one m (element-at? entries u28)))
            (r29 (claim-one m (element-at? entries u29)))
            (r30 (claim-one m (element-at? entries u30)))
            (r31 (claim-one m (element-at? entries u31)))
            (r32 (claim-one m (element-at? entries u32)))
            (r33 (claim-one m (element-at? entries u33)))
            (r34 (claim-one m (element-at? entries u34)))
            (r35 (claim-one m (element-at? entries u35)))
            (r36 (claim-one m (element-at? entries u36)))
            (r37 (claim-one m (element-at? entries u37)))
            (r38 (claim-one m (element-at? entries u38)))
            (r39 (claim-one m (element-at? entries u39)))
            (r40 (claim-one m (element-at? entries u40)))
            (r41 (claim-one m (element-at? entries u41)))
            (r42 (claim-one m (element-at? entries u42)))
            (r43 (claim-one m (element-at? entries u43)))
            (r44 (claim-one m (element-at? entries u44)))
            (r45 (claim-one m (element-at? entries u45)))
            (r46 (claim-one m (element-at? entries u46)))
            (r47 (claim-one m (element-at? entries u47)))
            (r48 (claim-one m (element-at? entries u48)))
            (r49 (claim-one m (element-at? entries u49)))
        )
        (let ((result {
                topic: "claim-many",
                manager: (contract-of m),
                submitted: (len entries),
                ok-count: (+ (get ok r0)
                    (get ok r1)
                    (get ok r2)
                    (get ok r3)
                    (get ok r4)
                    (get ok r5)
                    (get ok r6)
                    (get ok r7)
                    (get ok r8)
                    (get ok r9)
                    (get ok r10)
                    (get ok r11)
                    (get ok r12)
                    (get ok r13)
                    (get ok r14)
                    (get ok r15)
                    (get ok r16)
                    (get ok r17)
                    (get ok r18)
                    (get ok r19)
                    (get ok r20)
                    (get ok r21)
                    (get ok r22)
                    (get ok r23)
                    (get ok r24)
                    (get ok r25)
                    (get ok r26)
                    (get ok r27)
                    (get ok r28)
                    (get ok r29)
                    (get ok r30)
                    (get ok r31)
                    (get ok r32)
                    (get ok r33)
                    (get ok r34)
                    (get ok r35)
                    (get ok r36)
                    (get ok r37)
                    (get ok r38)
                    (get ok r39)
                    (get ok r40)
                    (get ok r41)
                    (get ok r42)
                    (get ok r43)
                    (get ok r44)
                    (get ok r45)
                    (get ok r46)
                    (get ok r47)
                    (get ok r48)
                    (get ok r49)),
                err-count: (+ (get err r0)
                    (get err r1)
                    (get err r2)
                    (get err r3)
                    (get err r4)
                    (get err r5)
                    (get err r6)
                    (get err r7)
                    (get err r8)
                    (get err r9)
                    (get err r10)
                    (get err r11)
                    (get err r12)
                    (get err r13)
                    (get err r14)
                    (get err r15)
                    (get err r16)
                    (get err r17)
                    (get err r18)
                    (get err r19)
                    (get err r20)
                    (get err r21)
                    (get err r22)
                    (get err r23)
                    (get err r24)
                    (get err r25)
                    (get err r26)
                    (get err r27)
                    (get err r28)
                    (get err r29)
                    (get err r30)
                    (get err r31)
                    (get err r32)
                    (get err r33)
                    (get err r34)
                    (get err r35)
                    (get err r36)
                    (get err r37)
                    (get err r38)
                    (get err r39)
                    (get err r40)
                    (get err r41)
                    (get err r42)
                    (get err r43)
                    (get err r44)
                    (get err r45)
                    (get err r46)
                    (get err r47)
                    (get err r48)
                    (get err r49)),
            }))
            (print result)
            (ok result))))

(define-public (settle-many
    (m <settleable-manager>)
    (entries (list 50 {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
    (let (
            (r0 (settle-one m (element-at? entries u0)))
            (r1 (settle-one m (element-at? entries u1)))
            (r2 (settle-one m (element-at? entries u2)))
            (r3 (settle-one m (element-at? entries u3)))
            (r4 (settle-one m (element-at? entries u4)))
            (r5 (settle-one m (element-at? entries u5)))
            (r6 (settle-one m (element-at? entries u6)))
            (r7 (settle-one m (element-at? entries u7)))
            (r8 (settle-one m (element-at? entries u8)))
            (r9 (settle-one m (element-at? entries u9)))
            (r10 (settle-one m (element-at? entries u10)))
            (r11 (settle-one m (element-at? entries u11)))
            (r12 (settle-one m (element-at? entries u12)))
            (r13 (settle-one m (element-at? entries u13)))
            (r14 (settle-one m (element-at? entries u14)))
            (r15 (settle-one m (element-at? entries u15)))
            (r16 (settle-one m (element-at? entries u16)))
            (r17 (settle-one m (element-at? entries u17)))
            (r18 (settle-one m (element-at? entries u18)))
            (r19 (settle-one m (element-at? entries u19)))
            (r20 (settle-one m (element-at? entries u20)))
            (r21 (settle-one m (element-at? entries u21)))
            (r22 (settle-one m (element-at? entries u22)))
            (r23 (settle-one m (element-at? entries u23)))
            (r24 (settle-one m (element-at? entries u24)))
            (r25 (settle-one m (element-at? entries u25)))
            (r26 (settle-one m (element-at? entries u26)))
            (r27 (settle-one m (element-at? entries u27)))
            (r28 (settle-one m (element-at? entries u28)))
            (r29 (settle-one m (element-at? entries u29)))
            (r30 (settle-one m (element-at? entries u30)))
            (r31 (settle-one m (element-at? entries u31)))
            (r32 (settle-one m (element-at? entries u32)))
            (r33 (settle-one m (element-at? entries u33)))
            (r34 (settle-one m (element-at? entries u34)))
            (r35 (settle-one m (element-at? entries u35)))
            (r36 (settle-one m (element-at? entries u36)))
            (r37 (settle-one m (element-at? entries u37)))
            (r38 (settle-one m (element-at? entries u38)))
            (r39 (settle-one m (element-at? entries u39)))
            (r40 (settle-one m (element-at? entries u40)))
            (r41 (settle-one m (element-at? entries u41)))
            (r42 (settle-one m (element-at? entries u42)))
            (r43 (settle-one m (element-at? entries u43)))
            (r44 (settle-one m (element-at? entries u44)))
            (r45 (settle-one m (element-at? entries u45)))
            (r46 (settle-one m (element-at? entries u46)))
            (r47 (settle-one m (element-at? entries u47)))
            (r48 (settle-one m (element-at? entries u48)))
            (r49 (settle-one m (element-at? entries u49)))
        )
        (let ((result {
                topic: "settle-many",
                manager: (contract-of m),
                submitted: (len entries),
                ok-count: (+ (get ok r0)
                    (get ok r1)
                    (get ok r2)
                    (get ok r3)
                    (get ok r4)
                    (get ok r5)
                    (get ok r6)
                    (get ok r7)
                    (get ok r8)
                    (get ok r9)
                    (get ok r10)
                    (get ok r11)
                    (get ok r12)
                    (get ok r13)
                    (get ok r14)
                    (get ok r15)
                    (get ok r16)
                    (get ok r17)
                    (get ok r18)
                    (get ok r19)
                    (get ok r20)
                    (get ok r21)
                    (get ok r22)
                    (get ok r23)
                    (get ok r24)
                    (get ok r25)
                    (get ok r26)
                    (get ok r27)
                    (get ok r28)
                    (get ok r29)
                    (get ok r30)
                    (get ok r31)
                    (get ok r32)
                    (get ok r33)
                    (get ok r34)
                    (get ok r35)
                    (get ok r36)
                    (get ok r37)
                    (get ok r38)
                    (get ok r39)
                    (get ok r40)
                    (get ok r41)
                    (get ok r42)
                    (get ok r43)
                    (get ok r44)
                    (get ok r45)
                    (get ok r46)
                    (get ok r47)
                    (get ok r48)
                    (get ok r49)),
                err-count: (+ (get err r0)
                    (get err r1)
                    (get err r2)
                    (get err r3)
                    (get err r4)
                    (get err r5)
                    (get err r6)
                    (get err r7)
                    (get err r8)
                    (get err r9)
                    (get err r10)
                    (get err r11)
                    (get err r12)
                    (get err r13)
                    (get err r14)
                    (get err r15)
                    (get err r16)
                    (get err r17)
                    (get err r18)
                    (get err r19)
                    (get err r20)
                    (get err r21)
                    (get err r22)
                    (get err r23)
                    (get err r24)
                    (get err r25)
                    (get err r26)
                    (get err r27)
                    (get err r28)
                    (get err r29)
                    (get err r30)
                    (get err r31)
                    (get err r32)
                    (get err r33)
                    (get err r34)
                    (get err r35)
                    (get err r36)
                    (get err r37)
                    (get err r38)
                    (get err r39)
                    (get err r40)
                    (get err r41)
                    (get err r42)
                    (get err r43)
                    (get err r44)
                    (get err r45)
                    (get err r46)
                    (get err r47)
                    (get err r48)
                    (get err r49)),
            }))
            (print result)
            (ok result))))

(define-public (payout-many
    (m <settleable-manager>)
    (stakers (list 50 principal)))
    (let (
            (r0 (payout-one m (element-at? stakers u0)))
            (r1 (payout-one m (element-at? stakers u1)))
            (r2 (payout-one m (element-at? stakers u2)))
            (r3 (payout-one m (element-at? stakers u3)))
            (r4 (payout-one m (element-at? stakers u4)))
            (r5 (payout-one m (element-at? stakers u5)))
            (r6 (payout-one m (element-at? stakers u6)))
            (r7 (payout-one m (element-at? stakers u7)))
            (r8 (payout-one m (element-at? stakers u8)))
            (r9 (payout-one m (element-at? stakers u9)))
            (r10 (payout-one m (element-at? stakers u10)))
            (r11 (payout-one m (element-at? stakers u11)))
            (r12 (payout-one m (element-at? stakers u12)))
            (r13 (payout-one m (element-at? stakers u13)))
            (r14 (payout-one m (element-at? stakers u14)))
            (r15 (payout-one m (element-at? stakers u15)))
            (r16 (payout-one m (element-at? stakers u16)))
            (r17 (payout-one m (element-at? stakers u17)))
            (r18 (payout-one m (element-at? stakers u18)))
            (r19 (payout-one m (element-at? stakers u19)))
            (r20 (payout-one m (element-at? stakers u20)))
            (r21 (payout-one m (element-at? stakers u21)))
            (r22 (payout-one m (element-at? stakers u22)))
            (r23 (payout-one m (element-at? stakers u23)))
            (r24 (payout-one m (element-at? stakers u24)))
            (r25 (payout-one m (element-at? stakers u25)))
            (r26 (payout-one m (element-at? stakers u26)))
            (r27 (payout-one m (element-at? stakers u27)))
            (r28 (payout-one m (element-at? stakers u28)))
            (r29 (payout-one m (element-at? stakers u29)))
            (r30 (payout-one m (element-at? stakers u30)))
            (r31 (payout-one m (element-at? stakers u31)))
            (r32 (payout-one m (element-at? stakers u32)))
            (r33 (payout-one m (element-at? stakers u33)))
            (r34 (payout-one m (element-at? stakers u34)))
            (r35 (payout-one m (element-at? stakers u35)))
            (r36 (payout-one m (element-at? stakers u36)))
            (r37 (payout-one m (element-at? stakers u37)))
            (r38 (payout-one m (element-at? stakers u38)))
            (r39 (payout-one m (element-at? stakers u39)))
            (r40 (payout-one m (element-at? stakers u40)))
            (r41 (payout-one m (element-at? stakers u41)))
            (r42 (payout-one m (element-at? stakers u42)))
            (r43 (payout-one m (element-at? stakers u43)))
            (r44 (payout-one m (element-at? stakers u44)))
            (r45 (payout-one m (element-at? stakers u45)))
            (r46 (payout-one m (element-at? stakers u46)))
            (r47 (payout-one m (element-at? stakers u47)))
            (r48 (payout-one m (element-at? stakers u48)))
            (r49 (payout-one m (element-at? stakers u49)))
        )
        (let ((result {
                topic: "payout-many",
                manager: (contract-of m),
                submitted: (len stakers),
                ok-count: (+ (get ok r0)
                    (get ok r1)
                    (get ok r2)
                    (get ok r3)
                    (get ok r4)
                    (get ok r5)
                    (get ok r6)
                    (get ok r7)
                    (get ok r8)
                    (get ok r9)
                    (get ok r10)
                    (get ok r11)
                    (get ok r12)
                    (get ok r13)
                    (get ok r14)
                    (get ok r15)
                    (get ok r16)
                    (get ok r17)
                    (get ok r18)
                    (get ok r19)
                    (get ok r20)
                    (get ok r21)
                    (get ok r22)
                    (get ok r23)
                    (get ok r24)
                    (get ok r25)
                    (get ok r26)
                    (get ok r27)
                    (get ok r28)
                    (get ok r29)
                    (get ok r30)
                    (get ok r31)
                    (get ok r32)
                    (get ok r33)
                    (get ok r34)
                    (get ok r35)
                    (get ok r36)
                    (get ok r37)
                    (get ok r38)
                    (get ok r39)
                    (get ok r40)
                    (get ok r41)
                    (get ok r42)
                    (get ok r43)
                    (get ok r44)
                    (get ok r45)
                    (get ok r46)
                    (get ok r47)
                    (get ok r48)
                    (get ok r49)),
                err-count: (+ (get err r0)
                    (get err r1)
                    (get err r2)
                    (get err r3)
                    (get err r4)
                    (get err r5)
                    (get err r6)
                    (get err r7)
                    (get err r8)
                    (get err r9)
                    (get err r10)
                    (get err r11)
                    (get err r12)
                    (get err r13)
                    (get err r14)
                    (get err r15)
                    (get err r16)
                    (get err r17)
                    (get err r18)
                    (get err r19)
                    (get err r20)
                    (get err r21)
                    (get err r22)
                    (get err r23)
                    (get err r24)
                    (get err r25)
                    (get err r26)
                    (get err r27)
                    (get err r28)
                    (get err r29)
                    (get err r30)
                    (get err r31)
                    (get err r32)
                    (get err r33)
                    (get err r34)
                    (get err r35)
                    (get err r36)
                    (get err r37)
                    (get err r38)
                    (get err r39)
                    (get err r40)
                    (get err r41)
                    (get err r42)
                    (get err r43)
                    (get err r44)
                    (get err r45)
                    (get err r46)
                    (get err r47)
                    (get err r48)
                    (get err r49)),
            }))
            (print result)
            (ok result))))
