;; Zero to Claiming batch helper, uint-return shape. One transaction claims for up
;; to 50 stakers against a manager whose claim-staker-rewards returns a bare uint:
;; the earlier reference revision that Xverse's deployment froze (managers are
;; immutable, so each deployment keeps whichever revision existed on deploy day).
;;
;; Same design rules as zc-claim-helper (claim-many.md): error isolation via
;; match, never try!, so one reverting staker cannot strand the batch; the helper
;; holds no funds and triggers only permissionless calls; per-entry prints plus a
;; batch summary let the app reconcile results from the transaction's events.
;; The uint return carries no withdrawal request id; on BTC payouts that id lives
;; in the manager's own l1-withdrawal print event, emitted in the same
;; transaction, so nothing is lost, only returned differently.
;; No settle-many or payout-many here: this revision predates the settle-and-
;; payout lineage and has neither function.
;; The per-entry bodies are mechanically unrolled: Clarity cannot carry a trait
;; reference through fold or map.

(define-trait claimable-manager-uint
  ((claim-staker-rewards (principal uint (optional uint)) (response uint uint))))

(define-private (claim-one-uint
    (m <claimable-manager-uint>)
    (oe (optional {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
  (match oe e
    (match (contract-call? m claim-staker-rewards (get staker e) (get reward-cycle e) (get bond-index e))
      r (begin
          (print {topic: "zc-claim-ok", staker: (get staker e), reward-cycle: (get reward-cycle e), earned: r})
          {ok: u1, err: u0})
      c (begin
          (print {topic: "zc-claim-err", staker: (get staker e), reward-cycle: (get reward-cycle e), code: c})
          {ok: u0, err: u1}))
    {ok: u0, err: u0}))

(define-public (claim-many
    (m <claimable-manager-uint>)
    (entries (list 50 {staker: principal, reward-cycle: uint, bond-index: (optional uint)})))
    (let (
            (r0 (claim-one-uint m (element-at? entries u0)))
            (r1 (claim-one-uint m (element-at? entries u1)))
            (r2 (claim-one-uint m (element-at? entries u2)))
            (r3 (claim-one-uint m (element-at? entries u3)))
            (r4 (claim-one-uint m (element-at? entries u4)))
            (r5 (claim-one-uint m (element-at? entries u5)))
            (r6 (claim-one-uint m (element-at? entries u6)))
            (r7 (claim-one-uint m (element-at? entries u7)))
            (r8 (claim-one-uint m (element-at? entries u8)))
            (r9 (claim-one-uint m (element-at? entries u9)))
            (r10 (claim-one-uint m (element-at? entries u10)))
            (r11 (claim-one-uint m (element-at? entries u11)))
            (r12 (claim-one-uint m (element-at? entries u12)))
            (r13 (claim-one-uint m (element-at? entries u13)))
            (r14 (claim-one-uint m (element-at? entries u14)))
            (r15 (claim-one-uint m (element-at? entries u15)))
            (r16 (claim-one-uint m (element-at? entries u16)))
            (r17 (claim-one-uint m (element-at? entries u17)))
            (r18 (claim-one-uint m (element-at? entries u18)))
            (r19 (claim-one-uint m (element-at? entries u19)))
            (r20 (claim-one-uint m (element-at? entries u20)))
            (r21 (claim-one-uint m (element-at? entries u21)))
            (r22 (claim-one-uint m (element-at? entries u22)))
            (r23 (claim-one-uint m (element-at? entries u23)))
            (r24 (claim-one-uint m (element-at? entries u24)))
            (r25 (claim-one-uint m (element-at? entries u25)))
            (r26 (claim-one-uint m (element-at? entries u26)))
            (r27 (claim-one-uint m (element-at? entries u27)))
            (r28 (claim-one-uint m (element-at? entries u28)))
            (r29 (claim-one-uint m (element-at? entries u29)))
            (r30 (claim-one-uint m (element-at? entries u30)))
            (r31 (claim-one-uint m (element-at? entries u31)))
            (r32 (claim-one-uint m (element-at? entries u32)))
            (r33 (claim-one-uint m (element-at? entries u33)))
            (r34 (claim-one-uint m (element-at? entries u34)))
            (r35 (claim-one-uint m (element-at? entries u35)))
            (r36 (claim-one-uint m (element-at? entries u36)))
            (r37 (claim-one-uint m (element-at? entries u37)))
            (r38 (claim-one-uint m (element-at? entries u38)))
            (r39 (claim-one-uint m (element-at? entries u39)))
            (r40 (claim-one-uint m (element-at? entries u40)))
            (r41 (claim-one-uint m (element-at? entries u41)))
            (r42 (claim-one-uint m (element-at? entries u42)))
            (r43 (claim-one-uint m (element-at? entries u43)))
            (r44 (claim-one-uint m (element-at? entries u44)))
            (r45 (claim-one-uint m (element-at? entries u45)))
            (r46 (claim-one-uint m (element-at? entries u46)))
            (r47 (claim-one-uint m (element-at? entries u47)))
            (r48 (claim-one-uint m (element-at? entries u48)))
            (r49 (claim-one-uint m (element-at? entries u49)))
        )
        (let ((result {
                topic: "claim-many",
                manager: (contract-of m),
                submitted: (len entries),
                ok-count: (+ (get ok r0)
                    (get ok r1)
                    (get ok r2)
                    (get ok r3)
                    (get ok r4)
                    (get ok r5)
                    (get ok r6)
                    (get ok r7)
                    (get ok r8)
                    (get ok r9)
                    (get ok r10)
                    (get ok r11)
                    (get ok r12)
                    (get ok r13)
                    (get ok r14)
                    (get ok r15)
                    (get ok r16)
                    (get ok r17)
                    (get ok r18)
                    (get ok r19)
                    (get ok r20)
                    (get ok r21)
                    (get ok r22)
                    (get ok r23)
                    (get ok r24)
                    (get ok r25)
                    (get ok r26)
                    (get ok r27)
                    (get ok r28)
                    (get ok r29)
                    (get ok r30)
                    (get ok r31)
                    (get ok r32)
                    (get ok r33)
                    (get ok r34)
                    (get ok r35)
                    (get ok r36)
                    (get ok r37)
                    (get ok r38)
                    (get ok r39)
                    (get ok r40)
                    (get ok r41)
                    (get ok r42)
                    (get ok r43)
                    (get ok r44)
                    (get ok r45)
                    (get ok r46)
                    (get ok r47)
                    (get ok r48)
                    (get ok r49)),
                err-count: (+ (get err r0)
                    (get err r1)
                    (get err r2)
                    (get err r3)
                    (get err r4)
                    (get err r5)
                    (get err r6)
                    (get err r7)
                    (get err r8)
                    (get err r9)
                    (get err r10)
                    (get err r11)
                    (get err r12)
                    (get err r13)
                    (get err r14)
                    (get err r15)
                    (get err r16)
                    (get err r17)
                    (get err r18)
                    (get err r19)
                    (get err r20)
                    (get err r21)
                    (get err r22)
                    (get err r23)
                    (get err r24)
                    (get err r25)
                    (get err r26)
                    (get err r27)
                    (get err r28)
                    (get err r29)
                    (get err r30)
                    (get err r31)
                    (get err r32)
                    (get err r33)
                    (get err r34)
                    (get err r35)
                    (get err r36)
                    (get err r37)
                    (get err r38)
                    (get err r39)
                    (get err r40)
                    (get err r41)
                    (get err r42)
                    (get err r43)
                    (get err r44)
                    (get err r45)
                    (get err r46)
                    (get err r47)
                    (get err r48)
                    (get err r49)),
            }))
            (print result)
            (ok result))))
